---
title: "Final projects!"
author: "BIOL4558"
date: "Noviembre 2021"
output:
  html_document: 
    theme: spacelab
    toc: yes
    toc_float: yes
    code_folding: hide
  pdf_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
```

## Proyecto Final BIOL 4558

Los estudiantes trabajarán en grupos de ~ 2-3 personas para realizar un análisis de viabilidad de la población (PVA) para clasificar las acciones de conservación o manejo para una especie de interés de conservación (¡especie de su elección!). La calificación se basará en los productos terminados (presentaciones escritas y orales), así como en la participación y evaluaciones de pares.

## Puntos importante

- Seleccionar una especie y una pregunta de interés.

- Realice una revisión exhaustiva de la literatura sobre su especie de interés; recopile toda la información que pueda sobre el historial de vida, las tasas vitales clave y su variabilidad.

- Construir un modelo PVA, parametrizado utilizando la mejor información disponible de la literatura (plataformas de software PVA gratuitas: InsightMaker o R).

- Utilice su modelo PVA para abordar una pregunta de conservación o manejo y _escriba los resultados_.

- ¡Presenta tus resultados a la clase!

## Cronología

- **PROPUESTA: ** ¡Vence el viernes 15 de noviembre!
- **PVA INICIAL ** Vence el viernes 22 de noviembre: descripción de cómo funciona su modelo PVA y de dónde provienen las estimaciones de los parámetros.
- ** ENVIAR EL BORRADOR PARA REVISIÓN POR PARES ** Vence el 24 de noviembre a las 5 p.m. (para revisión por pares el 26 de noviembre)
- **BORRADOR DEL DOCUMENTO FINAL: ** Se vence el miércoles 1 de diciembre a las 5 p.m.
- **DOCUMENTO FINAL FINAL: ** ¡El ultimo dia de clase!
- **PRESENTACIONES FINALES: ** ¡Los dos últimos días de las clases!


## Primera asignación relacionada con el proyecto: ¡la propuesta!

Su propuesta de proyecto (aproximadamente 1 pg) consistirá en:

1. **Título **: debe indicar qué especie está modelando y al menos insinuar qué pregunta se abordará
2. **Participantes del proyecto **: proporcione los nombres de todos los participantes (2-3).
3. **Pregunta (s) de investigación **: proporcione una o más preguntas comprobables y relevantes para la gestión que planea abordar utilizando su modelo de población.
4. **Justificación del proyecto **: Describa la justificación para elegir esta especie y la cuestión de gestión/conservación. ¡Sea lo más específico posible! ¡Convence a tus instructores de que tu proyecto es ** interesante **!
5. **Fuentes de datos **: Describa una o más fuentes de datos / información que planea usar para guiar la construcción y parametrización de PVA (¡queremos asegurarnos de que su proyecto sea **posible **!)  


**NOTA sobre las fuentes de datos:** 
 - Los parámetros más importantes que necesita para un modelo PVA son *tasas de supervivencia * (generalmente estructuradas por edad), *tasas de fecundidad * (a menudo también estructuradas por edad), *estocasticidad * (cantidad de variabilidad aleatoria en esas tasas vitales), *abundancia inicial *, *tasas de dispersión * y *capacidad de carga (K) *. 
 - Ya hemos repasado muchos de estos conceptos en clase: ¡PVA es solo una forma de unir todos estos conceptos en un solo modelo! Puede obtener estas estimaciones de parámetros directamente de la literatura publicada (o informes no publicados), o puede estimar estos parámetros usted mismo utilizando datos sin procesar (que aún no hemos revisado en clase). Si todo lo demás falla, puede usar registros publicados para especies similares (asumiendo que las tasas vitales son aproximadamente las mismas).

## Segunda asignación relacionada con el proyecto: ¡el PVA inicial!

Su PVA inicial parametrizado consistirá en:

1. Un modelo PVA listo para ejecutar, en cualquier marco de software que esté utilizando (InsightMaker, R). Este modelo no necesita ser el modelo "final", pero debería funcionar (por ejemplo, producir resultados) y las estimaciones de los parámetros deberían ser razonables y estar respaldadas por pruebas (ver más abajo).

2. Una justificación/evidencia escrita para cada una de sus estimaciones de parámetros y otras decisiones clave de modelado.

    A.  Para cada decisión importante que tomó al construir el modelo, describa la información que utilizó para respaldar su decisión (y la(s) fuente(s) de esta información). Las decisiones incluyen: cuántas poblaciones, abundancia(s) inicial(es), cuántas etapas, cómo opera la dependencia de la densidad para su especie (por ejemplo, qué tasas vitales dependen de la densidad), efectos Allee, tasas de supervivencia y fecundidad, estocasticidad ambiental, catástrofes, etc. Cuando sea apropiado, siéntase libre de incrustar figuras, mapas, etc. de sus fuentes de información.
    
    B. ¿Qué escenarios planea probar (por ejemplo, escenarios de manejo, cambio climático, cosecha, etc.) y cómo estos escenarios lo ayudarán a abordar sus preguntas de investigación?
    
    C. Literatura citada (el formato no es importante, siempre que incluya toda la información clave).        
    
## Tercera tarea relacionada con el proyecto: ¡el proyecto escrito (borrador)!

Se espera que su trabajo final escrito tenga el estilo de un **manuscrito científico **. Es decir, debe tener secciones de *introducción *, *métodos *, *resultados * y *discusión *, y debe citar la literatura relevante.


**No hay pautas de formato ni límites de página **. Sea lo más conciso posible sin dejar de cubrir todos los elementos clave de la rúbrica. Puede utilizar cualquier formato estándar para sus referencias, ¡todo lo que le pedimos es que sea coherente!

### Introducción
Aquí es donde presenta el tema y describe por qué es importante. También debe incluir aquí sus preguntas de investigación, junto con cualquier hipótesis que esté probando. ¡Puede reciclar y dar cuerpo al material de su propuesta! Debe tener al menos 2-3 párrafos.

### Métodos
Aquí es donde usted describe su PVA con suficiente detalle como para que *¡otro investigador de vida silvestre lo pueda replicar *!Puede reciclar gran parte de su asignación de "PVA inicial" aquí.

Recuerde justificar todas sus decisiones en términos de parametrización.

Además, debe describir cómo abordó las preguntas de investigación que presentó en la sección de introducción (arriba)

- ¿Qué diferentes escenarios corriste?

- ¿Cómo utilizó los resultados de la simulación para abordar sus preguntas?
    - ¿Cómo visualizó los resultados?
    - ¿Realizó algún análisis estadístico?     

### Resultados
Aquí es donde describe y presenta los resultados relevantes de su modelo (la mayoría se puede reciclar de su asignación de 'PVA final'). Proporcione figuras y tablas para resumir sus resultados *relevantes *. Debe incluir al menos 2-3 cifras como parte de su sección de resultados. Cada figura debe tener una leyenda informativa colocada directamente debajo de la figura.

Con PVA puede ser difícil decidir qué presentar y qué no presentar. Pregúntese siempre: ¿es * relevante * para sus preguntas principales??

### Discusión
Aquí es donde usted describe lo que realmente nos dicen sus resultados con respecto a sus preguntas principales.

Además, en su discusión debe incluir:

- Describa cualquier pregunta nueva que surgió en el proceso de construcción y ejecución de su PVA.
- Describe cualquier defecto potencial de tu PVA y cómo podrías mejorarlo en el futuro.
- Describa cualquier investigación futura que pueda ser útil para abordar sus principales preguntas.

Se puede encontrar una rúbrica para la presentación escrita final. [here](WrittenProject_rubric.docx). 


## Cuarta tarea relacionada con el proyecto: ¡la presentación oral!

La presentación de su grupo debe tener el estilo de una presentación oral en una conferencia. ¡Consulte a continuación para obtener orientación sobre cómo dar una buena presentación oral!

Las presentaciones se llevarán a cabo durante nuestros dos últimos períodos de laboratorio.

Tendrá 15 minutos para realizar sus presentaciones, con al menos 3 minutos adicionales para preguntas.

Le entregaremos un formulario simple de revisión por pares para que pueda dar su opinión a sus compañeros.

Se puede encontrar una rúbrica para las presentaciones. [here](presentationProject_rubric.docx)
=

### ¡Consejos para una gran presentación!

Aquí hay algunas notas generales sobre cómo preparar y realizar una gran presentación:
- Para todas las diapositivas: *¡Menos palabras, más imágenes *! Las diapositivas llenas de palabras a menudo hacen que las personas dejen de prestar atención. Todos ustedes están trabajando con especies carismáticas, por lo que no deberían tener problemas para encontrar buenas imágenes que capten la atención de las personas. En cuanto a las palabras, ¡3-5 puntos como máximo! NO se necesitan oraciones completas en una presentación. Utilice una fuente como por ejemplo *sans-serif* grande para mejorar la legibilidad.

Nota: asegúrese de dar el crédito adecuado a todas las imágenes (por ejemplo, ¿de qué sitio web proviene?)

- La emoción es contagiosa: asegúrese de transmitir su entusiasmo por el proyecto. Todos trabajaron muy duro y deberían estar orgullosos de lo que pudieron hacer. ¡Ahora puede compartir esta emoción con sus colegas! Muchos presentadores sin experiencia cometen el error de destacar solo lo que no pudieron lograr. Trate de evitar este escollo; las deficiencias deben limitarse a una sola diapositiva en la sección de discusión de la presentación.

- Una buena presentación debe *contar una historia *. Tiene un principio, un medio y un final. Cada diapositiva fluye lógicamente de lo que vino antes.

- Hágalo simple, no use jerga, acrónimos, etc. excesivos. Buenas habilidades de comunicación significan transmitir sus puntos de la manera más simple y clara posible.

- Cada presentación es una actuación. ¡El rendimiento requiere práctica! El trabajo real viene antes de la actuación: armar las diapositivas y practicar la presentación. Cuando llegue el momento de dar la actuación, relájese y diviértase, ¡el trabajo duro ha terminado!

Nota: no utilice fondos elegantes, mantenga las diapositivas lo más limpias posible. Las animaciones pueden ser útiles, ¡pero la animación excesiva es solo una distracción!


#### Diapositiva de título

- ¡Haz un título interesante!
- Incluya los nombres y afiliaciones de todos los coautores.

#### Introducción

- ¡Dile a tu audiencia por qué debería importarles! Todos ustedes están trabajando con especies interesantes y todos están haciendo preguntas interesantes. Toda su audiencia está interesada en la conservación y el manejo de la vida silvestre. ¡No hay absolutamente ninguna razón por la que no puedas convencer a tu audiencia de que se preocupe por lo que tienes que decir!

- Cite investigaciones anteriores al configurar su pregunta de investigación. Convéncenos de que su investigación llena un vacío de conocimiento clave. ¿Cuál es el contexto general de su investigación?

- Una vez que haya enmarcado el problema, *¡establezca claramente sus preguntas de investigación *!


#### Métodos

- Proporcione un resumen muy abreviado de su modelo PVA. ¡No tiene tiempo para proporcionar todos los detalles que se encuentran en su sección de Métodos escrita! Así que intente destilar los elementos clave de sus métodos. ¡Tenga cuidado de no dedicar demasiado tiempo a esta sección! Los detalles que proporcione aquí deben ser claramente relevantes para sus preguntas de investigación. Todo lo que necesita hacer es convencer a sus compañeros de que sus métodos fueron apropiados para abordar sus preguntas.

- Puede incluir diapositivas complementarias que brinden más detalles sobre sus métodos (después de la última diapositiva "real"). ¡Puede ser útil consultar las diapositivas complementarias si alguien hace una pregunta sobre sus métodos!


#### Resultados

- Incluir graficos claves que se relacionen con las preguntas principales.

- ¡Para todos los gráficos, asegúrese de explicar qué representan los ejes! Además, asegúrese de que las etiquetas de los ejes sean lo suficientemente grandes para que se puedan leer desde la parte posterior de la sala.


#### Discusión

- Resuma sus hallazgos clave: ¿qué aprendió?

- Implicaciones de manejo: ¿cómo podrían los administradores de vida silvestre actuar sobre sus hallazgos?

- Solo una diapositiva que analiza las deficiencias de su proyecto y cómo mejoraría su modelo y diseño si tuviera tiempo adicional.

- Describa lo que usted u otros investigadores podrían hacer para ampliar sus hallazgos. ¿Cuáles son los próximos pasos?


#### Agradecimientos

- Su diapositiva final debe reconocer a las personas que lo ayudaron con su proyecto pero que no figuran como coautores.






## Enlaces potencialmente útiles!

Conjuntos de datos disponibles públicamente, potencialmente para el proyecto final ...
(muchos enlaces cortesía de Tom Langen) 

### BIODIVERSITY DATA CLEARINGHOUSES /ARCHIVES
[International Union for the Conservation of Nature (IUCN) Redlist](http://www.iucnredlist.org/) (Searchable list of the world’s threatened and endangered plants and animal species on the IUCN Redlist.)  

[Conservation International Global Biodiversity Hotspots](http://www.biodiversityhotspots.org/Pages/default.aspx) (Detailed data on the attributes and threats to the world’s global biodiversity hotspots.)  

[National Biological Information Infrastructure](http://www.nbii.gov/) (Data archive and clearinghouse for biological data from the US. Also provides standards for metadata.)  

[Biological Inventories of the World’s Protected Areas](http://www.ice.ucdavis.edu/bioinventory/bioinventory.html) (Searchable species occurrence records and species lists for over 1,400 protected areas around the globe.)  

[Global Biodiversity Information Facility](http://data.gbif.org/welcome.htm) (An enormous clearinghouse of biodiversity data) 

[USGS avian data portal](https://migbirdapps.fws.gov/mbdc/databases/db_selection.html)     

[Global Population Dynamics Data Base(GPDD)](http://www3.imperial.ac.uk/cpb/research/patternsandprocesses/gpdd) (5000 population size time series for 1400 species, most of which have at least ten years of data. There are data on the natural history of the organism and the location & method of sampling.)   

[GPDD, alternative link](https://www.imperial.ac.uk/cpb/gpdd2/secure/login.aspx)     

[USGS Breeding Bird Survey](http://www.pwrc.usgs.gov/BBS/) (Breeding bird survey data back to 1966)  

[Bird Point Count Database](http://www.pwrc.usgs.gov/point/) (Depository of bird point-count data from across the US.)   

[Bird Studies Canada Nature Counts](http://www.bsc-eoc.org/birdmon/default/main.jsp) (Bird survey data archive for Canada, includes point counts and many other types of surveys.)  

[Avian Knowledge Network](http://www.avianknowledge.net/content/datasets)  (Archive of aggregated bird surveys from many organizations and studies across throughout the western hemisphere, including Latin America.)  

[NatureServe](http://www.natureserve.org/getData/index.jsp)  (Data on species of plants and animals in the Western Hemisphere, including detailed range maps) 

[USGS bat data portal](https://my.usgs.gov/bpd/)     
 
[Comadre and Compadre matrix demography database](https://compadredb.wordpress.com/2015/10/05/introducing-the-comadre-animal-matrix-database/)    

### GOVERNMENT AGENCY DATA PORTALS 

[National Atlas](http://www.nationalatlas.gov/) (Geospatial data on the environment, economy, and people of the US).   

[US Department of Agriculture Census of Agricultural Data](http://www.agcensus.usda.gov/) (Authoritative data on all aspects of agriculture in the US.)      

[Centers for Disease Control & Prevention Data & Statistics](http://www.cdc.gov/datastatistics/) (Comprehensive data on all aspects of disease epidemiology.)     

[USGS Water Data for the Nation](http://waterdata.usgs.gov/nwis) (Hydrological and water-quality data from across the US.)  

[USGS Survey Disease Maps](http://diseasemaps.usgs.gov/index.html) (US County-scale maps of incidence patterns of various mosquito-vectored diseases)    

[The Multi-resolution Land Characteristics Consortium (MRLC) National Land Cover Database](http://www.mrlc.gov/) (Land cover or land use, canopy cover, and impermeable surface area of the entire US, at a resolution of 30 m x 30 m, based on remote sensing data from satellite imagery.)  

[US Fish & Wildlife Service National Wetlands Inventory](http://www.fws.gov/wetlands/) (Wetlands greater than 1 acre are mapped and classified throughout the US, Puerto Rico and US territories. Data can be examined using the [Wetland Mapper](http://www.fws.gov/wetlands/Data/Mapper.html) and then downloaded for use by a GIS application, or can by inspected directly using [Google Earth](http://www.fws.gov/wetlands/Data/GoogleEarth.html))   

[USDA Forest Inventory and Analysis National Program](http://fia.fs.fed.us/) 
[Forest Inventory Data Online (FIDO)](http://fia.fs.fed.us/tools-data/default.asp) (Highly-detailed periodic surveys of forest composition at sites throughout the US.)   

[US Geological Survey](http://www.usgs.gov/) (Reports, data analysis, maps, and raw data on a diversity of topics related to environmental science, including biodiversity and emerging diseases.)

[NOAA National Climate Data Center](http://www.ncdc.noaa.gov/oa/ncdc.html) (Extensive data archives of climate data, including paleoclimate.)

### ENVIRONMENTAL DATA CLEARINGHOUSES
[Ecotrends](http://www.ecotrends.info/EcoTrends/) (Data archive and data visualization tools for ecological data at sites distributed around the US.)  

[NASA Global Change Master Directory](http://gcmd.nasa.gov/index.html) (Data on all aspects of global change, includes data on climate, land use, biodiversity and human dimensions.)  

[Oak Ridge National Laboratory Distributed Active Archive Center for Biogeochemical Dynamics(ORNL DAAC)](http://daac.ornl.gov/index.shtml) (A NASA-sponsored source for biogeochemical and ecological data and models useful in environmental research.)  

[Pole to Pole Ecological Research Lattice of Sites (P2ERLS)](http://www.p2erls.net/) (Portal to research stations and research networks, including their data archives.)  

[Weatherspark](http://weatherspark.com/) (Visualized time-series data on local climate at sites around the globe.)  

[Long Term Ecological Research (LTER) Network](http://www.lternet.edu/) (Network of research stations that have standardized monitoring programs as well as site-specific research. Sites are mandated to make data publicly available on the web.)  


### RESEARCH PROJECT DATA ARCHIVES
[Dryad](http://datadryad.org/) (Data archives for bioscience data from peer-reviewed journal articles from a large consortium of journals)   

[Ecological Society of America (ESA) Data Registry](http://esapubs.org/archive/archive_D.htm)
Archive of ecological and environmental data from ESA publications)  

[National Center for Ecological Assessment & Synthesis (NCEAS) Data Repository](http://knb.ecoinformatics.org/knb/style/skins/nceas/index.jsp) (Data archive of contributed data sets of all types of ecological data.)  

[NCEAS Scientific Computing Database](http://www.nceas.ucsb.edu/scicomp/) (Clearinghouse of climatological, geospatial, and other data. Also has shareware software for analysis.)
































