---
title: "BIOL4458"
author: "Raymond L. Tremblay"
date: "9/19/2021"
output_dir: 
  html_document: 
    theme: spacelab
    toc: yes
    toc_float: yes
    code_folding: hide
    creative_commons: CC BY
favicon: favicons/favicon.ico
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Invitados

En este documentos encontrarán información los invitados que trabaja en dinamica poblacional, conservación y PVA.

Se encontrará información sobre los invitados y un enlace para el articulo que DEBEN leer antes del dia.  Se le estará haciendo pregunta sobre los articulos leido. 


****



## 1. Martha Charitonidou
mirecoles, el 20 de octubre, 2021

 - Candidata al PhD
 - Laboratory of Ecology
 - Dept. of Biological Application and TECHNOLOGY
 - UNIVERSITY OF IOANNINA, GREECE.
 
 VEA EL SIGUIENTE ENLACE
 
 [M_CHARITONIDOU](https://www.researchgate.net/profile/Martha-Charitonidou)

### LEER EL SIGUIENTE ARTICULO
 
 [OPRHYS](Guest_Speakers/Charitonidou, Kougioumoutzis, Halley - 2021.pdf)
 
 
***
 
## 2. Dra. Demetria Mondragón

 - Especialista en plantas epifitas
 - Dinámica poblacional
 - Centro Interdisciplinario de Investigación para el Desarrollo Integral Regional, Unidad Oaxaca, México

 VEA EL SIGUIENTE ENLACE
 
[D_Mondragón](https://www.researchgate.net/profile/Demetria-Mondragon)

### LEER EL SIGUIENTE ARTICULO

[Variacion Temporal](Guest_Speakers/Temporal_variation_in_the_demography_of.pdf)


***

## 3. Dra. Nhora H. Ospina Calderon

- Especialista en dinamica poblacional
- Conservación
- Herbarium HUQ, Biology Program, University of Quindío, Armenia, Colombia.

[H Ospina](https://www.researchgate.net/profile/Nhora-Ospina-Calderon)

### LEER EL SIGUIENTE Documento

[Gustavia speciosa](PDF/Nhora__Opsina_ICCB_Poster_2017.pdf)


